config/routes.rb
Videopage::Application.routes.draw do

  devise_for :users

  root :to => 'pages#index'
  
  resources :videos
  resources :pages
  
  match "/embed/:id" => "videos#embed"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  has_many :videos
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :user_id, :panda_video_id
  
  belongs_to :user
  
  validates_presence_of :panda_video_id

  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    authenticate_user! rescue redirect_to new_user_session_path
    #@videos = Video.find_all_by_user_id(current_user.id)
    @videos = current_user.videos.all
  end

  def show
    authenticate_user! rescue redirect_to new_user_session_path
    
    @video = Video.find(params[:id])
    @original_video = @video.panda_video
    @h264_encoding = @original_video.encodings["h264.hi"]
    @webm_encoding = @original_video.encodings["webm"]
  end
  
  def embed
    @video = Video.find(params[:id])
    @original_video = @video.panda_video
    @h264_encoding = @original_video.encodings["h264.hi"]
    @webm_encoding = @original_video.encodings["webm"]
    
    render :layout => 'embed'
  end

  def new
    authenticate_user! rescue redirect_to new_user_session_path
    
    @video = Video.new
  end

  def create
    authenticate_user! rescue redirect_to new_user_session_path
    
    @video = Video.create!(params[:video])
    #redirect_to :action => :show, :id => @video.id
    redirect_to videos_path
  end

  def destroy
    authenticate_user! rescue redirect_to new_user_session_path
    
    video = Video.find(params[:id])
    video.panda_video.delete
    video.destroy
    flash[:success] = "Film zostal usuniety"
    redirect_to videos_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VideoPage</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag 'http://cdn.pandastream.com/u/1.4/jquery.panda-uploader.min.js' %>
		<link href="http://vjs.zencdn.net/c/video-js.css" rel="stylesheet">
		<script src="http://vjs.zencdn.net/c/video.js"></script>
		<%= csrf_meta_tags %> <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<%= link_to 'VideoPage', root_path, class: 'brand' %>
					<ul class="nav pull-right">
						<% if user_signed_in? %>
						<li>
							<%= link_to 'Twoje materiały video', videos_path %>
						</li>
						<li>
							<%= link_to 'Wrzuć nowy materiał', new_video_path %>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to 'Twoje konto', edit_user_registration_path %>
								</li>
								<li>
									<%= link_to 'Wyloguj się', destroy_user_session_path, method: :delete %>
								</li>
							</ul>
						</li>
						<% else %>
						<li class="active">
							<%= link_to 'Załóż nowe konto!', new_user_registration_path %>
						</li>
						<li>
							<%= link_to 'Zaloguj się', new_user_session_path %>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<% if !notice.nil? %>
			<p class="alert alert-info">
				<%= notice %>
			</p>
			<% end %>
			<% if !alert.nil? %>
			<p class="alert alert-error">
				<%= alert %>
			</p>
			<% end %>
			<div class="hero-unit">
				<%= yield %>
			</div>
		</div>
		<footer class="footer">
			<div class="container">
				<small>Wykonanie: <a href="http://socialfreaks.pl">Maciej Stasiełuk</a></small>
			</div>
		</footer>
		<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9631369-4']);
  _gaq.push(['_setDomainName', 'videopage.herokuapp.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	</body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VideoPage</title>
		<link href="http://vjs.zencdn.net/c/video-js.css" rel="stylesheet">
		<script src="http://vjs.zencdn.net/c/video.js"></script>
		<%= csrf_meta_tags %> <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<style type="text/css">
			* {
				margin: 0px;
				padding: 0px;	
			}
			body{
				width: 640px;
				height: 360px;
				overflow: hidden;
			}
		</style>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/pages/index.html.erb
<h2>Witamy w VideoPage.pl</h2>
<p>
	Dzięki potędze Cloud Computingu wydajne dostarczanie treści video w Internecie nigdy nie było tak proste i przyjemne. 
</p>
<p>
	Już dziś zapisz się do platformy VideoPage.pl i wzbogać swoją stronę interntową o treści multimedialne. 
</p>
<p>
	<%= link_to 'Załóż nowe konto!', new_user_registration_path, class: 'btn btn-primary btn-large' %>
</p>

app/views/videos/embed.html.erb
<video id="video-<%= @video.panda_video_id %>" class="video-js vjs-default-skin" controls
  preload="auto" width="640" height="360" poster="<%= @h264_encoding.screenshots.first %>"
  data-setup="{}">
  <source src="<%= @h264_encoding.url %>" type='video/mp4' />
  <source src="<%= @webm_encoding.url %>" type='video/webm' />
</video>

app/views/videos/index.html.erb
<div class="page-header">
  <h1>Lista Twoich filmów
  <%= link_to 'Wrzuć nowy materiał', new_video_path, class: 'btn btn-primary btn-large' %>
  </h1>
</div>
<div class="row-fluid">
	<ul class="thumbnails">
		<% @videos.each do |v| %>
		<li class="span4">
			<div class="thumbnail">
				<img src="<%= v.panda_video.encodings["h264.hi"].screenshots.first %>" width="300" alt="">
				<div class="caption">
					<h3><%= v.title %></h3>
					<% if v.panda_video.status == 'success' %>
					<p>Status: gotowy</p>
					<% else %>
					<p>Status: konwertowanie</p>
					<% end %>
					<p>
						<%= link_to 'Oglądaj', v, class: 'btn btn-success' %>
						<%= link_to "Usuń film", v, class: 'btn btn-danger',
						method: :delete, data: { confirm: "Czy na pewno chcesz usunąć ten film?" } %>
					</p>
				</div>
			</div>
		</li>
		<% end %>
	</ul>
</div>

app/views/videos/new.html.erb
<h2>Dodawanie nowego filmu</h2>

<%= form_for @video do |f| %>
  <p>
    <%= f.label :title, 'Tytuł' %>
    <%= f.text_field :title %>
  </p>

  <!-- the control will appear next to this, and the video ID will be stored here after the upload -->
  <input type="hidden" name="video[panda_video_id]" id="returned_video_id" />
  
  <input type="hidden" name="video[user_id]" value="<%= current_user.id %>" />

  <!-- upload progress bar (optional) -->
  <div id="upload_progress" class="panda_upload_progress"></div>


  <%= f.submit "Dodaj video" %>
<% end %>

<p>Maksymalny rozmiar pliku to 10MB!</p>

<script>
  <% auth_params = Panda.signed_params('post', "/videos.json") %>
  jQuery("#returned_video_id").pandaUploader(<%=raw auth_params.to_json %>, {
    // Uncomment the line below if your panda account is in the EU
    // api_host: 'api-eu.pandastream.com',
    upload_progress_id: 'upload_progress'
  });
</script>

app/views/videos/show.html.erb
<h2><%= @video.title %></h2>

<div style="margin: 20px 50px 0 0;">
<video id="video-<%= @video.panda_video_id %>" class="video-js vjs-default-skin" controls
  preload="auto" width="640" height="360" poster="<%= @h264_encoding.screenshots.first %>"
  data-setup="{}">
  <source src="<%= @h264_encoding.url %>" type='video/mp4' />
  <source src="<%= @webm_encoding.url %>" type='video/webm' />
</video>
</div>

<h3 style="margin-top: 50px;">Osadź na zewnętrznej stronie internetowej</h3>
<textarea style="width: 600px; height: 50px;"><iframe src="<%= url_for(:controller => 'videos', :action => 'embed', :id => @video.id, :only_path => false) %>" style="width: 640px; height: 360px;" frameborder="0" allowFullScreen="true"></iframe></textarea>

<div style="clear: both;"></div>